### PR TITLE
Fix: Type mismatch: inferred type is String? but String was expected

### PR DESCRIPTION
**Pull request by edapess**
e: file:///..../node_modules/@segment/analytics-react-native/android/src/main/java/com/segmentanalyticsreactnative/AnalyticsReactNativeModule.kt:128:30 Type mismatch: inferred type is String? but String was expected

### CODE REVIEW

**Comment by bhandanyan-nomad** [comment]
@thesunita could you please take a look at this one?

**Comment by BenHurMartins** [comment]
When this PR is going to be merged? I am trying to use a patch on react-native 0.76 and it is not working...

**Comment by JuanRdBO** [comment]
I need this too!

**Comment by JuanRdBO** [comment]
@alanjcharles

**Review by alanjcharles — APPROVED** [review]
thanks!

**Pull request merged**
