### PR TITLE
please, fix build.graddle!

### PR DESCRIPTION
**Pull request by juliandondero**
please, fix build.graddle y can't use the google analytics integration in android, the project name is wrong

### CODE REVIEW

**Comment by iyogeshjoshi** [comment]
@fathyb can you please review the change and merge it, it's breaking my code for long time now.

**Comment by f2prateek** [comment]
We'll take a look soon!

**Comment by iyogeshjoshi** [comment]
@fathyb hey I'm using same Gradle version 4.4 it's still breaking for me, though changing the path i.e, replacing `_` with `/` works for me. I'm not sure either why it is failing on CI.

**Comment by bsneed** [comment]
Made this change in PR #147, seems to be working/building fine.

**Pull request closed without merging**
