### PR TITLE
Niall/braze debounce update

### PR DESCRIPTION
**Pull request by niallzato**
Our current logic for comparing the last seen traits and the current traits does not actually compare values. Our current logic to compare the traits is just checking the referential equality:

`      
this.lastSeenTraits?.traits === event.traits
`

Referential equality can be determined with equality operators such as strict equality (===) or coercive equality (==) and also by using [Object.is](http://object.is/)() functions, but determining deep equality is tricky as the objects can be nested.

Customer issue: https://github.com/segmentio/analytics-react-native/issues/907

### CODE REVIEW

**Review by alanjcharles — COMMENTED** [review]
lgtm! Can you write a test for it in [identify.test.ts](https://github.com/segmentio/analytics-react-native/blob/master/packages/plugins/plugin-braze/src/methods/__tests__/identify.test.ts) ?

**Review by oscb — APPROVED** [review]

**Review by oscb — APPROVED** [review]

**Pull request merged**
