### PR TITLE
refactor: mark async storage and sovran as peer dependencies

### PR DESCRIPTION
**Pull request by mateusz1913**
Context: Follow-up PR for https://github.com/segmentio/sovran-react-native/pull/44

In the README, the installation instructions point to install `@segment/sovran-react-native` &
`@react-native-async-storage/async-storage`. In that case it doesn't make sense to include those as direct
dependencies.

### CODE REVIEW

**Comment by mateusz1913** [comment]
👋 is there sth I need to improve here?

**Comment by alanjcharles** [comment]
Hi  @mateusz1913 thanks for bringing this to our attention! It is definitely something we have considered and might take on in the future but we're not able to make this change at the moment. I'm going to close this out for now but please feel free to reach out with any additional concerns.

**Comment by mateusz1913** [comment]
Hi @alanjcharles, thx for reaching out. Is there any particular blocker that me (or anyone) can help resolve?

**Comment by shamilovtim** [comment]
@alanjcharles he's just ensuring that the community recommends against Segment's libraries when we're making new tooling decisions 👍

**Comment by alanjcharles** [comment]
@mateusz1913 we are planning to do this, but we need to fix it in sovran first too and we were in the middle of migrating the sovran repo. We're happy to convert them now that we have finished the migration. Thanks for your patience. 

@shamilovtim please refer to our [code of conduct](https://github.com/segmentio/analytics-react-native/blob/master/CODE_OF_CONDUCT.md) before posting. If you have actual issues, we're happy to take them on and prioritize them accordingly. Thanks.

**Comment by shamilovtim** [comment]
@alanjcharles You can [see my comment](https://github.com/segmentio/analytics-react-native/issues/655#issuecomment-1360045801) in December relating to your team's lack of adherence to basic principles of open source ticket management. This is a constant across tickets, repos and projects. Interesting that you cynically deployed COC to silence a simple negative review.

**Pull request closed without merging**
