### PR TITLE
Use KotlinVersion of root project if available 

### PR DESCRIPTION
**Pull request by hamidhadi**
### Description
After upgrading the gradle version of our project, `react-native` test task failed. 
This pull request is using Kotlin version from the root project if available to prevent android test task errors

### CODE REVIEW

**Comment by LaurenceRolandJames** [comment]
Is this going to get merged soon?

Thanks 🙏

**Comment by zatteo** [comment]
I've the following error trying the latest version :
```
* What went wrong:
A problem occurred evaluating project ':@segment_analytics-react-native'.
> Could not get unknown property 'defaultKotlinVersion' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

It seems to be related to this PR, am I doing something wrong ? 

Thanks !

**Comment by bsneed** [comment]
@zatteo not seeing that error here.  In packages/android/build.gradle, could you try removing line 4, and editing lines 16 and 45 where it's used with the actual 1.3.21 value and see if that resolves it for you?

**Comment by zatteo** [comment]
With :
4: `// def defaultKotlinVersion = '1.3.21'`
16: `classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${safeExtGet("kotlinVersion", "1.3.21")}"`
45:  `api "org.jetbrains.kotlin:kotlin-stdlib:${safeExtGet("kotlinVersion", "1.3.21")}"`

I get :
```
* What went wrong:
A problem occurred evaluating project ':@segment_analytics-react-native'.
> Could not find method safeExtGet() for arguments [kotlinVersion, 1.3.21] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```
-----------------
If I put it directly like this it works (like before the PR) :
`classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.21'`

**Pull request merged**
